version: "3.9"
services:

  app:
    build:
      context: ./backend/ 
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT     
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: mongo:6.0.4
    hostname: test_mongodb 
    restart: always    
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    expose:
      - 27017


 