class securities_short:
    __slots__ ='datestamp','instrument_id','list_section','supertype','instrument_type','instrument_category','trade_code','isin','registry_number','registry_date','emitent_full_name','inn','nominal','currency','issue_amount','decision_date','oksm_edr','only_emitent_full_name','reg_country','qualified_investor','has_prospectus','is_concession_agreement','is_mortgage_agent','included_during_creation','security_has_default','security_has_tech_default','included_without_compliance','retained_without_compliance','has_restriction_circulation','listing_level_hist','obligation_program_rn','coupon_percent','early_repayment','early_redemption','iss_boards','other_securities','disclosure_part_page','disclosure_rf_info_page'
    
    def __init__(self,
                 datestamp,
                 instrument_id,
                 list_section,
                 supertype,
                 instrument_type,
                 instrument_category,
                 trade_code,
                 isin,
                 registry_number,
                 registry_date,
                 emitent_full_name,
                 inn,
                 nominal,
                 currency,
                 issue_amount,
                 decision_date,
                 oksm_edr,
                 only_emitent_full_name,
                 reg_country,
                 qualified_investor,
                 has_prospectus,
                 is_concession_agreement,
                 is_mortgage_agent,
                 included_during_creation,
                 security_has_default,
                 security_has_tech_default,
                 included_without_compliance,
                 retained_without_compliance,
                 has_restriction_circulation,
                 listing_level_hist,
                 obligation_program_rn,
                 coupon_percent,
                 early_repayment,
                 early_redemption,
                 iss_boards,
                 other_securities,
                 disclosure_part_page,
                 disclosure_rf_info_page                
                ):

        self.datestamp=datestamp
        self.instrument_id=instrument_id
        self.list_section=list_section
        self.supertype=supertype
        self.instrument_type=instrument_type
        self.instrument_category=instrument_category
        self.trade_code=trade_code
        self.isin=isin
        self.registry_number=registry_number
        self.registry_date=registry_date
        self.emitent_full_name=emitent_full_name
        self.inn=inn
        self.nominal=nominal
        self.currency=currency
        self.issue_amount=issue_amount
        self.decision_date=decision_date
        self.oksm_edr=oksm_edr
        self.only_emitent_full_name=only_emitent_full_name
        self.reg_country=reg_country
        self.qualified_investor=qualified_investor
        self.has_prospectus=has_prospectus
        self.is_concession_agreement=is_concession_agreement
        self.is_mortgage_agent=is_mortgage_agent
        self.included_during_creation=included_during_creation
        self.security_has_default=security_has_default
        self.security_has_tech_default=security_has_tech_default
        self.included_without_compliance=included_without_compliance
        self.retained_without_compliance=retained_without_compliance
        self.has_restriction_circulation=has_restriction_circulation
        self.listing_level_hist=listing_level_hist
        self.obligation_program_rn=obligation_program_rn
        self.coupon_percent=coupon_percent
        self.early_repayment=early_repayment
        self.early_redemption=early_redemption
        self.iss_boards=iss_boards
        self.other_securities=other_securities
        self.disclosure_part_page=disclosure_part_page
        self.disclosure_rf_info_page=disclosure_rf_info_page   	
