version: "3.9"
services:


  mongo:
    image: mongo:6.0.4 
    restart: always    
    environment:
      #- MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - web_trade_mongodata2:/data/db  
    #expose:
    #  - ${mongo_port}   
volumes:
  web_trade_mongodata2:     
    external: true  